apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetcore-api
  name: dotnetcore-api
spec:
  ports:
  - name: 6001-tcp
    port: 6001
    protocol: TCP
    targetPort: 6001
  selector:
    app: dotnetcore-api
  sessionAffinity: None
  type: ClusterIP
