apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:211d8e926b547b4381f060b1e1b2047553ff455660f0c7b812c168758a11f8c7
  name: quay.io/rh-ee-srehman/dotnetcore
  newName: quay.io/rh-ee-srehman/dotnetcore
